---
    - name: Clone chezmoi
      git: repo=https://github.com/kevinjqiu/chezmoi.git
           dest="{{chezmoi_dir}}"
    - name: Install chezmoi (symbolic links)
      command: "rake link_all"
      args:
        chdir: "{{chezmoi_dir}}"
    - name: Clone dot_bash
      git: repo=https://github.com/kevinjqiu/dot_bash.git
           dest="{{dotbash_dir}}"
    - name: Install dot_bash
      command: "{{dotbash_dir}}/install.sh"
      args:
        chdir: "{{dotbash_dir}}"
    - name: Install vimmy
      command: "{{chezmoi_dir}}/vim-bootstrap.sh {{chezmoi_dir}}/vimmy"
      args:
        chdir: "{{chezmoi_dir}}"
