---
    - name: Ensure git is installed
      sudo: yes
      apt: pkg=git-core state=latest update_cache=yes
    - name: Clone chezmoi
      git: repo=https://github.com/kevinjqiu/chezmoi.git
           dest="{{chezmoi_dir}}"
    - name: Clone dot_bash
      git: repo=https://github.com/kevinjqiu/dot_bash.git
           dest="{{dotbash_dir}}"
    - name: Install dot_bash
      command: "{{dotbash_dir}}/install.sh"
      args:
        chdir: "{{dotbash_dir}}"
